<#
.SYNOPSIS
  Generate the WiX file manifest (files.generated.wxs) from the cmake --install stage dir.

.DESCRIPTION
  WiX v6 has neither the v7 "Files" extension (<files:Files Include="..."/>) nor heat.exe,
  so this script walks the stage directory and emits Component/File entries itself:
    * one Component per file (the MSI component rule recommendation), Guid="*" lets WiX
      derive a stable GUID from the key path, which is what upgrades need;
    * the directory tree mirrors the real layout (platforms/, tls/, styles/, licenses/ ...);
    * the file list follows the Qt version automatically - hand-copying Qt DLLs into a build
      directory (what this project used to do) is exactly what breaks when Qt is bumped.

  NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads UTF-8-without-BOM files as
  ANSI, which corrupts non-ASCII comments and can break parsing.

.PARAMETER StageDir
  Directory produced by cmake --install (miderhive.exe, Qt DLLs, plugin subdirs, licenses/).

.PARAMETER OutFile
  Path of the .wxs file to write.

.PARAMETER PerUser
  When set (default), components get an HKCU registry value as their KeyPath. ICE38 requires
  this for anything installed under the user profile: a file cannot be the key path there,
  because a per-user package may be installed for several users on the same machine and each
  user needs its own component state.
#>
param(
    [Parameter(Mandatory = $true)][string]$StageDir,
    [Parameter(Mandatory = $true)][string]$OutFile,
    [switch]$PerMachine
)

$ErrorActionPreference = "Stop"
$StageDir = (Resolve-Path $StageDir).Path
if (-not (Test-Path (Join-Path $StageDir "miderhive.exe"))) {
    throw "stage dir has no miderhive.exe: $StageDir (run cmake --install first)"
}

function XmlEsc([string]$s) {
    return $s.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;').Replace('"', '&quot;')
}

# relative dir ('' = install root) -> files in it
$byDir = @{}
Get-ChildItem -Path $StageDir -Recurse -File | ForEach-Object {
    $rel = $_.DirectoryName.Substring($StageDir.Length).TrimStart('\')
    if (-not $byDir.ContainsKey($rel)) { $byDir[$rel] = New-Object System.Collections.ArrayList }
    [void]$byDir[$rel].Add($_)
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
[void]$sb.AppendLine('<!-- generated by scripts/gen-wix-files.ps1 - do not edit by hand -->')
[void]$sb.AppendLine('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')

# ---- directory tree ----
$subDirs = @($byDir.Keys | Where-Object { $_ -ne '' } | Sort-Object)
if ($subDirs.Count -gt 0) {
    [void]$sb.AppendLine('  <Fragment>')
    [void]$sb.AppendLine('    <DirectoryRef Id="INSTALLFOLDER">')
    foreach ($d in $subDirs) {
        $id = "dir_" + ($d -replace '[^A-Za-z0-9]', '_')
        [void]$sb.AppendLine(('      <Directory Id="{0}" Name="{1}" />' -f $id, (XmlEsc $d)))
    }
    [void]$sb.AppendLine('    </DirectoryRef>')
    [void]$sb.AppendLine('  </Fragment>')
}

# ---- components: one per file ----
# Deterministic component GUIDs, derived from the install-relative path.
# WiX rejects Guid="*" for components that mix a registry key path with files (WIX0230),
# and a path-derived GUID is what upgrades need anyway: the same file keeps the same
# component identity across versions, so an upgrade replaces it instead of duplicating it.
function ComponentGuid([string]$relPath) {
    $md5 = [System.Security.Cryptography.MD5]::Create()
    try {
        $bytes = $md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes("MiderHive.Component/$relPath"))
    } finally {
        $md5.Dispose()
    }
    return ([System.Guid]::new($bytes)).ToString().ToUpper()
}

$n = 0
$removedDirs = @{}
[void]$sb.AppendLine('  <Fragment>')
[void]$sb.AppendLine('    <ComponentGroup Id="AppFiles">')
foreach ($d in ($byDir.Keys | Sort-Object)) {
    if ($d -eq '') { $dirId = 'INSTALLFOLDER' } else { $dirId = "dir_" + ($d -replace '[^A-Za-z0-9]', '_') }
    foreach ($f in ($byDir[$d] | Sort-Object Name)) {
        $n++
        $c = "cmp_{0:D4}" -f $n
        $fid = "fil_{0:D4}" -f $n
        $relPath = if ($d -eq '') { $f.Name } else { "$d/$($f.Name)" }
        $guid = ComponentGuid $relPath
        [void]$sb.AppendLine(('      <Component Id="{0}" Directory="{1}" Guid="{2}">' -f $c, $dirId, $guid))
        if ($PerMachine) {
            # Program Files install: the file itself may be the key path
            [void]$sb.AppendLine(('        <File Id="{0}" Source="{1}" KeyPath="yes" />' -f $fid, (XmlEsc $f.FullName)))
        } else {
            # User-profile install: ICE38 requires an HKCU registry value as the key path
            [void]$sb.AppendLine(('        <File Id="{0}" Source="{1}" />' -f $fid, (XmlEsc $f.FullName)))
            [void]$sb.AppendLine(('        <RegistryValue Root="HKCU" Key="Software\MiderHive\Components" Name="{0}" Type="integer" Value="1" KeyPath="yes" />' -f $c))
        }
        # ICE64: every directory created under the user profile must be registered for
        # removal, otherwise uninstalling leaves empty folders behind. One RemoveFolder
        # per directory (attached to the first component that lives in it) is enough.
        $dirsToRemove = @()
        if (-not $removedDirs.ContainsKey($dirId)) {
            $removedDirs[$dirId] = $true
            $dirsToRemove += $dirId
            # Removing a subdirectory also requires the install root to be removable
            if ($dirId -ne 'INSTALLFOLDER' -and -not $removedDirs.ContainsKey('INSTALLFOLDER')) {
                $removedDirs['INSTALLFOLDER'] = $true
                $dirsToRemove += 'INSTALLFOLDER'
            }
        }
        foreach ($rd in $dirsToRemove) {
            [void]$sb.AppendLine(('        <RemoveFolder Id="rmf_{0}" Directory="{1}" On="uninstall" />' -f $rd, $rd))
        }
        [void]$sb.AppendLine('      </Component>')
    }
}
[void]$sb.AppendLine('    </ComponentGroup>')
[void]$sb.AppendLine('  </Fragment>')
[void]$sb.AppendLine('</Wix>')

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), $utf8NoBom)
Write-Host "GEN_WIX_FILES=$OutFile ($n files, $($subDirs.Count) subdirs)"
